on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'FreeBSD release'
        required: true
        type: choice
        options:
        - '15.0'
        - '14.2-pre'
        - '14.1'
        - '14.0'
        - '13.4'
        - '13.3'
        - '13.2'
        - '12.4'
        default: '14.1'

name: freebsd.yaml

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: r-hub/actions/setup-r-freebsd@abcba171160794c449c994f558d4573f248842ce # v1.8.0
        with:
          release: ${{ github.event.inputs.release || '14.1' }}
      - uses: r-hub/actions/platform-info@abcba171160794c449c994f558d4573f248842ce # v1.8.0

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2-branch
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2-branch
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
