on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'OpenBSD release'
        required: true
        type: choice
        options:
        - '7.9'
        - '7.8'
        - '7.7'
        default: '7.9'

name: openbsd.yaml

jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: r-hub/actions/setup-r-openbsd@02be5ffbeae2b0d553da66acded089da11a1fb8f # v1.8.1
        with:
          release: ${{ github.event.inputs.release || '7.9' }}
      - uses: r-hub/actions/platform-info@02be5ffbeae2b0d553da66acded089da11a1fb8f # v1.8.1

      - name: Install system packages
        run: |
          pkg_add -I libuv libbind
          cd /usr/local/lib && ln -s libbind/libbind.so* .
        shell: openbsd {0}

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2-branch
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2-branch
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
