on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'OpenBSD release'
        required: true
        type: choice
        options:
        - '7.6'
        - '7.5'
        - '7.4'
        default: '7.6'

name: openbsd.yaml

jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: r-hub/actions/setup-r-openbsd@cf6c8eff3145ef225104294e6b0c023de4bba9c6 # v1.7.7
        with:
          release: ${{ github.event.inputs.release || '7.6' }}
      - uses: r-hub/actions/platform-info@cf6c8eff3145ef225104294e6b0c023de4bba9c6 # v1.7.7

      - name: Install system packages (for pingr)
        run: |
          pkg_add -I libbind
          cd /usr/local/lib && ln -s libbind/libbind.so* .
        shell: openbsd {0}

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2-branch
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2-branch
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
